<?php

/**
 * Monitoring test bootstrap file.
 */

use Drupal\monitoring\Result\SensorResultInterface;

/**
 * Implements hook_menu().
 */
function monitoring_test_menu() {
  $items['monitoring/test_service'] = array(
    'title' => 'Test',
    'page callback' => 'monitoring_test_endpoint',
    'access callback' => TRUE,
    'type' => MENU_CALLBACK,
  );

  return $items;
}

/**
 * Implements of hook_ctools_plugin_api().
 */
function monitoring_test_ctools_plugin_api($module, $api) {
  if ($module == 'services' && $api == 'services') {
    return array(
      'version' => 3,
      'file' => 'monitoring_test.default_services.inc',
      'path' => drupal_get_path('module', 'monitoring_test'),
    );
  }
}

function monitoring_test_cron_queue_info() {
  $queues['monitoring_test'] = array(
    'worker callback' => 'monitoring_test_queue_worker',
    'time' => 60,
  );
  return $queues;
}

function monitoring_test_queue_worker() {

}

/**
 * Implements monitoring_MODULE_monitoring_sensor_info().
 */
function monitoring_monitoring_test_monitoring_sensor_info() {
  $info = array(
    'test_sensor_integration' => array(
      'label' => 'Test from integration hook',
      'description' => 'To test correct sensor info hook implementation precedence.',
      'sensor_class' => 'Drupal\monitoring_test\Sensor\Sensors\TestSensor',
      'settings' => array(
        'result_logging' => FALSE,
        'category' => 'Test',
      ),
    ),
    'watchdog_aggregate_test' => array(
      'label' => 'Watchdog aggregate test',
      'description' => 'Test sensor for watchdog aggregate.',
      'sensor_class' => 'Drupal\monitoring\Sensor\Sensors\SensorDatabaseAggregator',
      'settings' => array(
        'result_logging' => FALSE,
        'category' => 'Test',
        'thresholds' => array(
          'intervals' => array(
            SensorResultInterface::STATUS_CRITICAL => 2,
            SensorResultInterface::STATUS_WARNING => 1,
          ),
        ),
        'table' => 'watchdog',
      ),
    ),
    'db_aggregate_test' => array(
      'label' => 'DB Aggregate test',
      'description' => 'Tests the generic DB aggregate sensor.',
      'sensor_class' => 'Drupal\monitoring\Sensor\Sensors\SensorDatabaseAggregator',
      'value_label' => 'Druplicons',
      'result_logging' => TRUE,
      'settings' => array(
        'category' => 'Test',
        'table' => 'node',
        'conditions' => array(
          array('field' => 'promote', 'value' => '1'),
        ),
        'time_interval_field' => 'created',
        'time_interval_value' => 24 * 60 * 60,
        'thresholds' => array(
          'type' => 'falls',
          'intervals' => array(
            SensorResultInterface::STATUS_CRITICAL => 1,
            SensorResultInterface::STATUS_WARNING => 2,
          ),
        ),
      ),
    ),
    'test_sensor' => array(
      'label' => 'Test sensor',
      'description' => 'Test sensor status',
      'sensor_class' => 'Drupal\monitoring_test\Sensor\Sensors\TestSensor',
      'settings' => array(
        'result_logging' => TRUE,
        'category' => 'Test',
        'caching_time' => 3600,
        'thresholds' => array(
          'intervals' => array(
            SensorResultInterface::STATUS_CRITICAL => NULL,
            SensorResultInterface::STATUS_WARNING => NULL,
          ),
        ),
      ),
    ),
    'test_sensor_inner' => array(
      'label' => 'Test sensor inner',
      'description' => 'Test sensor that sets inner error intervals',
      'sensor_class' => 'Drupal\monitoring_test\Sensor\Sensors\TestSensor',
      'settings' => array(
        'result_logging' => TRUE,
        'category' => 'Test',
        'thresholds' => array(
          'type' => 'inner_interval',
          'intervals' => array(
            SensorResultInterface::STATUS_CRITICAL => array(4, 6),
            SensorResultInterface::STATUS_WARNING => array(1, 9),
          ),
        ),
      ),
    ),
    'test_sensor_outer' => array(
      'label' => 'Test sensor outer',
      'description' => 'Test sensor that sets outer error intervals',
      'sensor_class' => 'Drupal\monitoring_test\Sensor\Sensors\TestSensor',
      'settings' => array(
        'result_logging' => TRUE,
        'category' => 'Test',
        'thresholds' => array(
          'type' => 'outer_interval',
          'intervals' => array(
            SensorResultInterface::STATUS_CRITICAL => array(60, 90),
            SensorResultInterface::STATUS_WARNING => array(70, 80),
          ),
        ),
      ),
    ),
    'test_sensor_exceeds' => array(
      'label' => 'Test sensor exceeds',
      'description' => 'Test sensor that sets error interval above give value',
      'sensor_class' => 'Drupal\monitoring_test\Sensor\Sensors\TestSensor',
      'settings' => array(
        'result_logging' => TRUE,
        'category' => 'Test',
        'thresholds' => array(
          'intervals' => array(
            SensorResultInterface::STATUS_CRITICAL => 10,
            SensorResultInterface::STATUS_WARNING => 5,
          ),
        ),
      ),
    ),
    'test_sensor_falls' => array(
      'label' => 'Test sensor falls',
      'description' => 'Test sensor that sets error interval below give value',
      'sensor_class' => 'Drupal\monitoring_test\Sensor\Sensors\TestSensor',
      'settings' => array(
        'result_logging' => TRUE,
        'category' => 'Test',
        'thresholds' => array(
          'type' => 'falls',
          'intervals' => array(
            SensorResultInterface::STATUS_CRITICAL => 5,
            SensorResultInterface::STATUS_WARNING => 10,
          ),
        ),
      ),
    ),
    'test_sensor_cat_watchdog' => array(
      'label' => 'Test sensor category Watchdog',
      'description' => 'Test sensor with Watchdog category to test the watchdog logging',
      'sensor_class' => 'Drupal\monitoring_test\Sensor\Sensors\TestSensor',
      'settings' => array(
        'category' => 'Watchdog',
      ),
    ),
  );

  // In case we have testing_sensor_info data we add it as a new sensor.
  // See MonitoringApiTest::testAPI() for usage.
  $testing_sensor_info = variable_get('monitoring_test_sensor_info');
  if (!empty($testing_sensor_info)) {
    $info['test_sensor_info'] = $testing_sensor_info;
  }

  return $info;
}

/**
 * Endpoint callback.
 *
 * Purpose of this endpoint is to provide a proof of concept. There is no
 * test coverage for this as it adds no value, use it just for development
 * purposes.
 */
function monitoring_test_endpoint() {
  drupal_page_is_cacheable(FALSE);

  $sensor_name = $_GET['sensor'];
  try {
    $result = monitoring_sensor_run($sensor_name);
    drupal_json_output(array(
      'sensor_value' => $result->getSensorValue(),
      'sensor_message' => $result->getSensorMessage(),
      'sensor_status' => $result->getSensorStatus(),
    ));
  }
  catch (InvalidArgumentException $e) {
    return MENU_NOT_FOUND;
  }
}
