monitoring_multigraph.*:
  type: mapping
  label: 'Monitoring Multigraph'
  mapping:
    id:
      type: string
      label: 'Machine-readable name'
    label:
      type: label
      label: 'Multigraph Label'
    description:
      type: text
      label: 'Description'
    sensors:
      type: sequence
      label: 'Sensors'
      sequence:
        - type: mapping
          mapping:
            weight:
              type: integer
            label:
              type: string
