<?php
/**
 * @file
 * Monitoring multigraph bootstrap file.
 */

/**
 * Implements hook_help().
 */
function monitoring_multigraph_help($route_name) {
  switch ($route_name) {
    case 'monitoring.multigraphs_overview':
      $output = '<p>' . t('A monitoring <em>multigraph</em> is a bundle of monitoring sensors. This functionality provides monitoring multigraph information to 3rd party applications.') . '</p>';
      return $output;

    case 'monitoring.multigraph_add':
    case 'monitoring.multigraph_edit':
      $output = '<p>' . t('To store a monitoring <em>multigraph</em> first provide basic information (label/description), then select and add sensors to add them to this multigraph.<br />* Please note that all changes are not saved until the form is submitted using the <b>Save</b> button.') . '</p>';
      return $output;
  }
}
